---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listings
  template:
    metadata:
      labels:
        app: listings
    spec:
      containers:
      - name: main
        image: quay.io/mhausenblas/noteless-listings:0.2
        ports:
        - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: listings
  labels:
    app: listings
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9898
    protocol: TCP
  selector:
    app: listings
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: listings
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: listings
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: listings
              servicePort: 80